name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: |
          cd ./quasar-project && npm install
          npm install axios@^0.21.1
          npm install vue-i18n@^9.0.0
          npm install pinia@^2.0.11
          npm install @quasar/extras@^1.0.0
          npm install quasar@^2.6.0
          npm install vue@^3.0.0
          npm install vue-router@^4.0.0
          npm install --save-dev electron-builder

      - name: Build
        run: cd ./quasar-project && npm run build-electron

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.1
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ matrix.os }}${{ github.run_id }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./quasar-project/dist/electron/
          asset_name: electron-app.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
